# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'http.ui'
#
# Created: Tue Apr 11 10:31:49 2017
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(683, 596)
        Frame.setFrameShape(QtGui.QFrame.StyledPanel)
        Frame.setFrameShadow(QtGui.QFrame.Raised)
        self.pushButton = QtGui.QPushButton(Frame)
        self.pushButton.setGeometry(QtCore.QRect(140, 350, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.widget = QtGui.QWidget(Frame)
        self.widget.setGeometry(QtCore.QRect(30, 390, 551, 171))
        self.widget.setObjectName("widget")
        self.lineEdit_13 = QtGui.QLineEdit(self.widget)
        self.lineEdit_13.setGeometry(QtCore.QRect(12, 10, 591, 141))
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.frame = QtGui.QFrame(Frame)
        self.frame.setGeometry(QtCore.QRect(30, 40, 621, 291))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.lineEdit = QtGui.QLineEdit(self.frame)
        self.lineEdit.setGeometry(QtCore.QRect(20, 30, 31, 21))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtGui.QLineEdit(self.frame)
        self.lineEdit_2.setGeometry(QtCore.QRect(120, 30, 301, 21))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.commandLinkButton = QtGui.QCommandLinkButton(self.frame)
        self.commandLinkButton.setGeometry(QtCore.QRect(510, 20, 101, 41))
        self.commandLinkButton.setObjectName("commandLinkButton")
        self.pushButton_2 = QtGui.QPushButton(self.frame)
        self.pushButton_2.setGeometry(QtCore.QRect(430, 210, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.lineEdit_3 = QtGui.QLineEdit(self.frame)
        self.lineEdit_3.setGeometry(QtCore.QRect(10, 70, 113, 20))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtGui.QLineEdit(self.frame)
        self.lineEdit_4.setGeometry(QtCore.QRect(10, 100, 113, 20))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtGui.QLineEdit(self.frame)
        self.lineEdit_5.setGeometry(QtCore.QRect(10, 130, 113, 20))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtGui.QLineEdit(self.frame)
        self.lineEdit_6.setGeometry(QtCore.QRect(10, 160, 113, 20))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.lineEdit_7 = QtGui.QLineEdit(self.frame)
        self.lineEdit_7.setGeometry(QtCore.QRect(10, 190, 113, 20))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.lineEdit_8 = QtGui.QLineEdit(self.frame)
        self.lineEdit_8.setGeometry(QtCore.QRect(140, 70, 113, 20))
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.lineEdit_9 = QtGui.QLineEdit(self.frame)
        self.lineEdit_9.setGeometry(QtCore.QRect(140, 100, 113, 20))
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.lineEdit_10 = QtGui.QLineEdit(self.frame)
        self.lineEdit_10.setGeometry(QtCore.QRect(140, 160, 113, 20))
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.lineEdit_11 = QtGui.QLineEdit(self.frame)
        self.lineEdit_11.setGeometry(QtCore.QRect(140, 130, 113, 20))
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.lineEdit_12 = QtGui.QLineEdit(self.frame)
        self.lineEdit_12.setGeometry(QtCore.QRect(140, 190, 113, 20))
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.label_2 = QtGui.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(20, 10, 54, 12))
        self.label_2.setObjectName("label_2")
        self.comboBox = QtGui.QComboBox(self.frame)
        self.comboBox.setGeometry(QtCore.QRect(60, 30, 51, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox_2 = QtGui.QComboBox(self.frame)
        self.comboBox_2.setGeometry(QtCore.QRect(450, 30, 51, 22))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.label_3 = QtGui.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(433, 10, 81, 20))
        self.label_3.setObjectName("label_3")
        self.label = QtGui.QLabel(Frame)
        self.label.setGeometry(QtCore.QRect(40, 10, 54, 12))
        self.label.setObjectName("label")
        self.pushButton_3 = QtGui.QPushButton(Frame)
        self.pushButton_3.setGeometry(QtCore.QRect(420, 350, 75, 23))
        self.pushButton_3.setObjectName("pushButton_3")

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        Frame.setWindowTitle(QtGui.QApplication.translate("Frame", "Frame", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("Frame", "start", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_13.setText(QtGui.QApplication.translate("Frame", "null", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit.setText(QtGui.QApplication.translate("Frame", "URL", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_2.setText(QtGui.QApplication.translate("Frame", "http://www.baidu.com", None, QtGui.QApplication.UnicodeUTF8))
        self.commandLinkButton.setText(QtGui.QApplication.translate("Frame", "检查host", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_2.setText(QtGui.QApplication.translate("Frame", "clear", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_3.setText(QtGui.QApplication.translate("Frame", "key", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_4.setText(QtGui.QApplication.translate("Frame", "key", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_5.setText(QtGui.QApplication.translate("Frame", "key", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_6.setText(QtGui.QApplication.translate("Frame", "key", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_7.setText(QtGui.QApplication.translate("Frame", "key", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_8.setText(QtGui.QApplication.translate("Frame", "value", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_9.setText(QtGui.QApplication.translate("Frame", "value", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_10.setText(QtGui.QApplication.translate("Frame", "value", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_11.setText(QtGui.QApplication.translate("Frame", "value", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_12.setText(QtGui.QApplication.translate("Frame", "value", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Frame", "参数", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(0, QtGui.QApplication.translate("Frame", "get", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(1, QtGui.QApplication.translate("Frame", "post", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(2, QtGui.QApplication.translate("Frame", "head", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(3, QtGui.QApplication.translate("Frame", "delete", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_2.setItemText(0, QtGui.QApplication.translate("Frame", "true", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_2.setItemText(1, QtGui.QApplication.translate("Frame", "false", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Frame", "https证书校验", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Frame", "接口调试", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_3.setText(QtGui.QApplication.translate("Frame", "clear", None, QtGui.QApplication.UnicodeUTF8))

